services:
  - type: web
    name: money-manager-backend
    env: node
    plan: free
    branch: main  # or your deployment branch
    region: oregon
    buildCommand: npm install
    startCommand: node index.js  # or npm start or nodemon index.js
    envVars:
      - key: MONGO_URI
        value: your_MongoDB_URI
      - key: JWT_SECRET
        value: Your_JWT_token
      - key: PORT
        value: 4000
