services:
  - type: web
    name: money-manager-backend
    env: node
    plan: free
    region: oregon
    branch: main  # make sure this is the branch you want to deploy

    buildCommand: npm install
    startCommand: node index.js  # or "npm start" if you defined a start script

    envVars:
      - key: MONGODB_URI
        value: monbodburl
      - key: JWT_SECRET
        value: JWT_SECRET
      - key: RESEND_API_KEY
        value: resend
      - key: EMAIL_USER
        value: optional     # optional, if using email fallback
      - key: EMAIL_PASS
        value: optional   # optional, if using nodemailer fallback
      - key: PORT
        value: 4000
