services:
  - type: web
    name: money-manager-backend
    env: node
    plan: free
    region: oregon
    branch: main  # make sure this is the branch you want to deploy

    buildCommand: npm install
    startCommand: node index.js  # or "npm start" if you defined a start script

    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://turjot:Papiya5533@cluster0.y8qhs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: eyJS0me$Th1ngSup3rS3cure_456!@#uNtRuSTabLeKey
      - key: RESEND_API_KEY
        value: re_9BKHoSRU_FjoRb7HE3WM3rQJcSnouX2hz
      - key: EMAIL_USER
        value: princetalukder99@gmail.com       # optional, if using email fallback
      - key: EMAIL_PASS
        value: kujy setq jlrg lmwf    # optional, if using nodemailer fallback
      - key: PORT
        value: 4000
